### ISSUE TITLE
Blender 2.90 - Cannot apply all modifiers

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#10]
# Issue
![image](https://user-images.githubusercontent.com/35357409/87713147-5d5e9b80-c76f-11ea-9cc4-fb47de8f91e5.png)

When trying to apply any modifier or apply all modifiers, I will get errors like the mentioned above. Apply_As seems to not be recognized. 

Blender Version: 2.90 Alpha
Addon Version: 1.5.6

**Comment by Symstract** [comment]
Thanks for the report. I've fixed the bug in Modifier List 1.6. I'll try to release it soon. I'll keep this open until then.

**Comment by Draise14** [comment]
Oh that's wonderful news. Your addon not working with this is the only thing holding me back to a former 2.9 build from a month ago. 

I have to say, your modifier list organization, features and UX is far superior than Vanilla Blender. You've saved me a lot of time and work with this. 

Can't wait for the next release.

**Comment by Symstract** [comment]
1.6 is out, so closing now.
