### ISSUE TITLE
Weld Modifier - Missing Max property

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#11]
# Issue

There is a missing property in the weld modifier that pulls a console error:

`C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.91\scripts\addons\modifier_list\modules\ui\properties_data_modifier.py:1672
rna_uiItemR: property not found: WeldModifier.max_interactions`

# Task
Find out where the RNA is or remove the property. 

### Info
Blender 2.91 Beta / Bforartists 2.5.1

**Comment by Symstract** [comment]
Thanks for the report. The addon is a bit outdated so there are also thing missing, like Mesh to Volume and Volume to Mesh modifiers, boolean modifier is missing settings (solver most importantly) and some other things as well. I'll update this at some point when I have time. Before the 2.91 release at least.
