### ISSUE TITLE
Missing - Geometry Nodes modifier

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#13]
# Issue
![image](https://user-images.githubusercontent.com/35357409/101725236-41d99180-3a7e-11eb-9a10-49b1c1059b14.png)
The geometry nodes modifier is not listed, causes an error in console. 

Blender 2.92 Alpha

**Comment by Symstract** [comment]
Geometry Nodes are now supprted in Modifier List 1.6.3: https://github.com/Symstract/modifier_list/releases

(Sorry for the long delay, awful support...)
