### ISSUE TITLE
Can't identify modifiers without memorizing icons

### ISSUE THREAD

**Issue by alinsavix** [Symstract/modifier_list#14]
First off, this is an awesome addon, very much appreciate the efforts. <3

Second, actual feature request/bug:  Currently, if you rename a modifier, there's no way to find out what *type* of modifier a modifier is, unless you have the icon for that particular type of modifier memorized (or pull up the modifier list again to compare). It would be really nice if there was some way to directly identify what type of modifier a given entry in the list is, without requiring humans to do heuristics.

If the blender API allows for it, the fix might be as simple as adding a tooltip to the icon next to the modifier. I'd be quite happy with whatever you'd care to support, though. Not picky!

**Comment by Symstract** [comment]
Thanks for the suggestion. 

I don't know of a good way to add a tooltip that shows the modifier type. So unfortunately it's unlikely that I would be working on this.

(Sorry for the long delay, terrible support)
