### ISSUE TITLE
bug: can't register add-on because of corrupt prefrences.json file

### ISSUE THREAD

**Issue by daxbo** [Symstract/modifier_list#16]
Hi there, today my modifier list stopped working.
After some research I found out whats causing the trouble.
My preferences file is zero kbyte.
I don't know how that happend....
Anyway, once the addon tries to read that prefs file it runs into a error.
Could you add some safety checks to avoid issues like that?

regards.

btw. i'm using Blender Version: 2.93

**Comment by Symstract** [comment]
Hi, sorry for the delay. 

I can add a check for that in the next version.

You should be able to fix the problem by deleting the file, in case you didn't already figure that out.

**Comment by Symstract** [comment]
Resolved by 12b319fec934f0f6108749ef70b4d18a3c14611f
