### ISSUE TITLE
Update to Blender 3.0.0

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#17]
# Issue
![image](https://user-images.githubusercontent.com/35357409/116293134-271d6600-a75c-11eb-8500-f1c98c1cd05e.png)
I found that with the dev builds of 3.0.0 the version string to float of the BLENDER_VERSION_MAJOR_POINT_MINOR has to be 3 characters, not 4 to work. 

# Example Fix
[modifier_list_1.6.4.zip](https://github.com/Symstract/modifier_list/files/6386750/modifier_list_1.6.4.zip)

**Comment by Symstract** [comment]
Thanks for the report, I'll release an update in the next few days.

Also, thanks for the example fix but it will just reverse the problem making the addon only work properly in Blender 3. :D A better solution would be `float(bpy.app.version_string[0:4].strip("."))`.

**Comment by Draise14** [comment]
Oh thanks, I don't know a lot of python, I just dug in to fix the issue so I could keep using your addon. Thanks for the pointer! I updated the scripts with the `version_string`.

**Comment by Symstract** [comment]
Resolved by 897aedd5608c88e8dba240c09d72ff5a2ba8c946
