### ISSUE TITLE
'Toggle Visibility Of All Modifiers' shortcut doesn't work in edit mode.

### ISSUE THREAD

**Issue by kosztao** [Symstract/modifier_list#18]
Button works in edit mode, but after assigning shortcut to it shortcut doesn't work. Outside of edit mode everything works fine.

![2021-05-16 12_47_20-Window](https://user-images.githubusercontent.com/84271037/118394420-e6bb5480-b644-11eb-861c-2da11cd5853e.png)

**Comment by Symstract** [comment]
Thanks for the report.

I just need to change object.ml_toggle_all_modifiers to view3d.ml_toggle_all_modifiers and the shortcut will work also in other modes than object mode. I'll include the fix in the next patch.

**Comment by Symstract** [comment]
Resolved by b1ba6735ae788d246bbc4e2b6ad1d1b9a5a3fd77
