### ISSUE TITLE
Geometry Nodes - Object Input and Collection Input fields greyed out.

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#21]
# Expectation
Expected result, input for objects and collections to be able to pick (from the modifier stack.) 
![bforartists_XGAKEQYPjm](https://user-images.githubusercontent.com/35357409/123494459-888b7500-d5e5-11eb-9039-22f66b341a23.png)

# Issue
![bforartists_EMwDWMyBfD](https://user-images.githubusercontent.com/35357409/123494477-94773700-d5e5-11eb-8bed-13c677245926.png)

Tested in 2.93 and 3.0 with version 1.6.4

**Comment by Symstract** [comment]
Thanks for the report. This looks like a bug/limitation in Blender, I'll investigate and likely create a bug report.

**Comment by Symstract** [comment]
Solved in 1.7.
