### ISSUE TITLE
There is no "toggle edit mode visibility" in boolean modifiers when in list mode

### ISSUE THREAD

**Issue by Rivgar** [Symstract/modifier_list#22]
Expectation
![image](https://user-images.githubusercontent.com/46659437/129726120-a00131d9-a6b9-4f12-8369-a618e2f69960.png)
Issue
![image](https://user-images.githubusercontent.com/46659437/129726286-a6567ae6-a50b-4652-94d9-6e4c00ac3e4e.png)
Tested with 1.7 and 3.0 blender daily build

**Comment by Symstract** [comment]
Thanks for the report, awful mistake from me to miss this. New version is now available.

**Comment by Rivgar** [comment]
Hope you are well and thank you, I love this addon, but this feature been deal breaker before for me since I use a lot of bools but now that it is fixed I love it even more. I thought there was a limitation to this but after searching through issue page I found that no one posted about it so I gave a shot
