### ISSUE TITLE
List View breaks some Geometry Node Inputs

### ISSUE THREAD

**Issue by wojtekmichalak** [Symstract/modifier_list#26]
When building a Circular Array Geometry Node Template I had some custom Group Inputs not being recognized.
Troubleshooting that problem I traced it back to the Modifier List Addon, which I love.

With the List View being active, several inputs just don´t work.
List View ON:
![image](https://user-images.githubusercontent.com/47480624/151153895-4996d42c-c1c9-4198-95e4-c043ec03fc24.png)
List View OFF:
![image](https://user-images.githubusercontent.com/47480624/151154223-7b3e99f1-1584-449a-8561-aad5b5647286.png)
The Geometry Node Setup:
![image](https://user-images.githubusercontent.com/47480624/151154043-6f6d8d3a-adca-45f1-bb1d-28528aa4aa69.png)

Here´s a Link to the file:
[https://uploadify.net/560d0d601d9aecc8/CircularArray.blend](https://uploadify.net/560d0d601d9aecc8/CircularArray.blend)

Hope this helps.
Thx for the awesome addon.

**Comment by Symstract** [comment]
Thanks for the report, I've fixed the issue and I'll release a new patch soon.
