### ISSUE TITLE
geo node attribute out put not working

### ISSUE THREAD

**Issue by adhhrg** [Symstract/modifier_list#29]
no attribute output is displayed

**Comment by Symstract** [comment]
It seems to work for me in both 3.1 and 3.2 Alpha:

![image](https://user-images.githubusercontent.com/45314857/157500361-a004b304-fe34-448d-befb-21bfa7f03802.png)

Just to be sure, you do have some outputs connected? If so, can you provide some more information on how to reproduce the issue?
