### ISSUE TITLE
Library override disables all rows

### ISSUE THREAD

**Issue by razcore-rad** [Symstract/modifier_list#34]
In the image below I first disabled the Modifier List addon and changed `Vertices` just to check that they are actually editable in the default layout. Then I reactivated the addon and all modifiers are uneditable.

![image](https://user-images.githubusercontent.com/1177508/199727853-607c27e9-9f85-4d0d-aa0c-5f62064d47c3.png)

**Comment by Symstract** [comment]
Here is finally a new release...
https://github.com/Symstract/modifier_list/releases/tag/v1.7.5
