### ISSUE TITLE
Issues in blender 3.5

### ISSUE THREAD

**Issue by EdwHopper** [Symstract/modifier_list#35]
Modifier Add, Remove, Apply are just throwing errors like this:
![image](https://user-images.githubusercontent.com/68294820/209129255-361bf51b-c2bf-4f2d-81e9-2136728bda97.png)

**Comment by Draise14** [comment]
Can confirm, there are some issues with 3.5

Maybe a development build that works with the Blender Master/Main would be handy to future proof this addon? I do use master based builds in studio for work, this addon is indispensable! 

![image](https://user-images.githubusercontent.com/35357409/219069278-5f08de78-c949-4582-a323-57738b0c1b80.png)

**Comment by Symstract** [comment]
Does this still happen? At least I don't have any errors when using the operators.

@Draise14 That error is not specific to 3.5 but it will be fixed in the next version. And thanks for the suggestion but there's no need for a separate build, this just needs to be updated more regularly.

**Comment by Symstract** [comment]
I assume the issue was resolved.
