### ISSUE TITLE
Minor Issue occuring when there is no objects in the scene

### ISSUE THREAD

**Issue by Akhura** [Symstract/modifier_list#36]
As stated in the header, minor error arising when there is no objects in the scene at all, and when the cursor is placed in the Outliner Context.
![image](https://user-images.githubusercontent.com/88729252/210399216-a451325a-8a7e-448f-8d9c-d496ca428711.png)
![image](https://user-images.githubusercontent.com/88729252/210399286-6e14e878-fde0-40e5-b6eb-9ad25af64f38.png)

That's nothing serious really, but still, found a solution to this issue by adding another check condition to the "Poll" function.

![image](https://user-images.githubusercontent.com/88729252/210399624-e86829ea-c46e-4343-898a-adafc4a619c9.png)

**Comment by Symstract** [comment]
Here is finally a new release...
https://github.com/Symstract/modifier_list/releases/tag/v1.7.5
