### ISSUE TITLE
String input in Geometry Nodes is not Shown

### ISSUE THREAD

**Issue by ssnd292** [Symstract/modifier_list#37]
Hello Antti,

first of all: I absolutely love Modifier List, and in my opinion, it should be standard UI for modifier in Blender.

To the bug: 

With Modifier List 1.7.4 and Blender 3.4.1 the input for Strings in the Geometry Node input is not visible.
![2023-01-12 07_28_21-Einstellungen](https://user-images.githubusercontent.com/3914410/211993923-cf7a17bb-785c-41d3-a713-5245daf2de3f.jpg)

![2023-01-12 07_28_26-Einstellungen](https://user-images.githubusercontent.com/3914410/211993940-ad118abb-33d4-45ce-b21f-347bc271136f.jpg)<

Thank you.

**Comment by Symstract** [comment]
Here is finally a new release...
https://github.com/Symstract/modifier_list/releases/tag/v1.7.5

**Comment by ssnd292** [comment]
Thank you very much @Symstract !
