### ISSUE TITLE
Issue Installing 1.7.5

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#39]
![image](https://user-images.githubusercontent.com/35357409/232545211-65d1d5f3-662f-49a7-ac20-40bdbb65bbdc.png)

Right now the installation zip doesn't install to a sub folder for the `__init__.py` to register - and when I try to get the addon to register I get an issue, might be likely due to the parent folder name?

**Comment by Draise14** [comment]
yeah, found it. The zipped installation doesn't contain a sub folder called `modifier_list` meaning it won't install it correctly. 

![image](https://user-images.githubusercontent.com/35357409/232545935-0aae91aa-5d01-4803-9666-7702c0da593b.png)

**Comment by Symstract** [comment]
Well, that didn't go very well, thanks for the report! I replaced the incorrect zip.
