### ISSUE TITLE
Feature Req: Discard disabled modifiers before using "Apply all modifiers" or "Apply Modifier"

### ISSUE THREAD

**Issue by Neltulz** [Symstract/modifier_list#4]
I sometimes will disable a modifier (such as a subdiv modifier), and leave the modifier.  (Disable realtime viewport and render)

Well, whenever I apply all modifiers, or apply the modifier, blender's default behavior is to re-enable the modifier before applying it.

I consider that undesirable.  Can you add an option in your addon to automatically discard modifiers that are disabled in realtime viewport before applying the modifier?

Additionally, can you add a popup warning that says something like, "some of your modifiers are disabled in the realtime viewport, but enabled in render, how would you like to proceed?"

Option A: Discard modifier(s)
Option B: Keep modifier(s) & apply

This, to me, seems like a fool proof way to ensure that the user doesn't accidentally apply a handful of intentionally disabled modifiers when applying all modifiers.

Thanks!

**Comment by Symstract** [comment]
Thanks for the suggestion, I can add that.

**Comment by Neltulz** [comment]
Cool, thanks! :)

**Comment by Symstract** [comment]
About the popup: is it often that you have modifiers that are disabled in viewport but enabled in render and want to apply? Currently, I've made it so that modifiers that are disabled in viewport are always just skipped (no popup, Apply Modifier gives a "Modifier is hidden in viewport, skipped apply" message).  I can see myself using it too. So, I was just wondering is the popup warning necessary? Can you give some examples when that would be useful?

**Comment by Neltulz** [comment]
> About the popup: is it often that you have modifiers that are disabled in viewport but enabled in render and want to apply? Currently, I've made it so that modifiers that are disabled in viewport are always just skipped (no popup, Apply Modifier gives a "Modifier is hidden in viewport, skipped apply" message). I can see myself using it too. So, I was just wondering is the popup warning necessary? Can you give some examples when that would be useful?

I rarely have modifiers disabled in viewport yet enabled in render. I am still quite new to blender and have not yet taken advantage of all the cool features yet. So to make things simple, you can go with the simpler option here. There really doesnt seem any point to apply a modifier if it's visible in render yet disabled in viewport.

Thanks for asking! :)

**Comment by Symstract** [comment]
Implemented in 071249ed8974767e0cfe0dc38157d4bfa9c0e8d0
