### ISSUE TITLE
Add a option to customize the tab

### ISSUE THREAD

**Issue by xan2622** [Symstract/modifier_list#7]
Hi.

With more and more add-ons adding a tab in the N panel, the later can easily become vertically overcrowded by tabs (especially if the user has many addons activated).

To get rid of this annoyance (with many tabs on the N panel, it can be difficult to read the titles of these tabs), some users might want to place your add-on in the *Edit* or in the *View* tab... (or elsewhere).

Here is a related topic about this issue: https://blender.community/c/rightclickselect/dzdbbc/ 

According to the number of votes, there are many Blender users who are annoyed by this issue. The only workaround (for the moment) is to add an option in the addon preferences.

Could you please add **an option** in the add-on preferences **to give the user the choice of the location of the tab** (in the N panel) ? (in order to move the add-on from its own _Modifier List_ tab to a custom one).

---

Maybe you could have a look at the source code of these (free) add-ons (to reuse the lines related to this feature)?

**Backface Hiding** :  https://gitlab.com/ChameleonScales/Backface_Hiding

![6cb58ec90d0eaf2859819909e32075473fcd9f47](https://user-images.githubusercontent.com/1732773/79038461-b7cce680-7bd9-11ea-8eb7-97311b8566ba.jpeg)

**SpeedRetopo** : https://gumroad.com/l/speedretopo

![1173cda700ee4af649f858070ca426f970587afb](https://user-images.githubusercontent.com/1732773/79038462-bc919a80-7bd9-11ea-9d6f-d518dd2f198e.jpeg)

Thank you in advance for considering to add this option.

**Comment by Symstract** [comment]
Hi,

Thanks for the suggestion, I can add that in the next minor release.

**Comment by Symstract** [comment]
Implemented in 693e43a9e5737204f6efa79388b8e0b4575def8d. Will be in version 1.6, whenever that comes out.
