### ISSUE TITLE
A unkonwn modifier on modifier UI

### ISSUE THREAD

**Issue by KeshiSmith** [Symstract/modifier_list#8]
There is a new modifier named Surface when I enable the addon.  If I try to add it, it will show:

> "Cannot add Surface modifier for this object type"

Is it a bug or a function of addon? Look forward to your reply. Thanks.

![Imgur](https://i.imgur.com/VDeg2Sd.png)

**Comment by Symstract** [comment]
Thanks for the report. It was a bug.

Here's a patch: https://github.com/Symstract/modifier_list/releases/tag/v1.5.3
